<?php
/**
 * Created by PhpStorm.
 * User: wyd
 * Date: 2017-09-05
 * Time: 9:32
 */
//\Common\Helpers\StringHelper::dd($a,false);

//foreach ($a['rows'] as $row) {
//   // echo $row['id'];
//}

//\Common\Helpers\StringHelper::dd($a);
?>
<?php //foreach ($a['rows'] as $key => $value): ?>
<!---->
<?php //endforeach ?>

<script>
        $.ajax({
            url:'http://agent.e.com/index/indexa',
            dataType:'json',
            success:function () {
                
            }
        })

</script>
