<?php
/**
 * web提示信息模板 不能有任何可能的错误！修改一定小心！！
 */
if (!isset($time)) {
    if (\Common\Helpers\ConfigHelper::isDebug()) {
        $time = 2000;
    } else {
        $time = 5;/*两秒后跳转*/
    }
}
$goUrl=isset($goUrl)?$goUrl:'javascript:history.go(-1);';
$message=isset($message)?$message:"未知信息";
$title=isset($title)?$title:'提示信息';
$assetUri = isset($assetUri) ? $assetUri : 'http://static.e.com/';
$inDialog=\Common\Helpers\HttpHelper::isInDialog();
$boxWidthStyle=$inDialog?'width:80%;':'width:50%;';
?>
<?php if (!$inDialog): ?>
    <!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
    <title><?= $title ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/font-awesome/4.5.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/jquery-ui.min.css"/>
    <link rel="stylesheet" href="<?php echo $assetUri; ?>ace/css/ui.jqgrid.min.css"/>
    <!-- text fonts -->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/fonts.googleapis.com.css"/>
    <!-- ace styles -->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style"/>
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-part2.min.css" class="ace-main-stylesheet"/>
    <![endif]-->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-skins.min.css"/>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-rtl.min.css"/>
</head>
<body>
<div id="navbar" class="navbar navbar-default ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <div class="navbar-header pull-left">
            <a href="/" class="navbar-brand">
                <small>
                    <i class="fa fa-leaf"></i>
                    e家神灯管理系统
                </small>
            </a>
        </div>
    </div><!-- /.navbar-container -->
</div>
<?php endif ?>

<div class="main-container ace-save-state" id="main-container">
    <div class="main-content">
        <div class="main-content-inner">
            <div class="row">
                <div style="<?=$boxWidthStyle?>margin-left:auto;margin-right:auto;margin-top:1px;">
                    <div class="widget-box">
                        <div class="widget-header">
                            <h4 class="smaller text-center"><?php echo $title ?></h4>
                        </div>
                        <div class="widget-body">
                            <div class="widget-main text-center">
                                <div class="muted">
                                    <div style="font-size: 18px;word-break: break-all">
                                        <?php echo $message; ?>
                                    </div>
                                    <a href='<?php echo $goUrl ?>'>
                                        <?php echo $time; ?>秒后跳转，如果浏览器没有反应，请点击此处...
                                    </a>
                                    <script type="text/javascript">
                                        setTimeout(function () {
                                            location.href = '<?php echo $goUrl;?>';
                                        },<?php echo $time * 1000?>);
                                    </script>
                                </div>
                                <hr/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.main-content -->




    <?php if (!$inDialog): ?>
    <div class="footer" style="padding-top: 35px">
        <div class="footer-inner">
            <div class="footer-content" style="margin: 0;padding: 0;border-top: solid 1px #E5E5E5;line-height: normal">
                <span class="bigger-100">
                    <span class="blue bolder">汇川集团</span>&copy; 2013-<?php echo date('Y') + 1 ?>
                </span>
            </div>
        </div>
    </div>
</div><!-- /.main-container -->
</body>
</html>
<?php endif ?>
