<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
    <?php echo $this->tag->getTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/font-awesome/4.5.0/css/font-awesome.min.css"/>

    <!-- text fonts -->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/fonts.googleapis.com.css"/>

    <!-- ace styles -->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace.min.css"/>

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-part2.min.css"/>
    <![endif]-->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-rtl.min.css"/>

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-ie.min.css"/>
    <![endif]-->
    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->
    <!--[if lte IE 8]>
    <script src="<?= $assetUri ?>ace/js/html5shiv.min.js"></script>
    <script src="<?= $assetUri ?>ace/js/respond.min.js"></script>
    <![endif]-->
</head>
<body class="login-layout">
<div class="main-container">
    <div class="main-content">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="login-container">
                    <div class="center">
                        <h1>
                            <i class="ace-icon fa fa-leaf green"></i>
                            <span class="red">E家神灯管理系统</span>
                            <br>
                            <span class="white" id="id-text2">商家管理系统</span>
                        </h1>
                        <h4 class="blue" id="id-company-text">&copy; 汇川集团</h4>
                    </div>

                    <div class="space-6"></div>
                    <div class="position-relative">
                        <div id="login-box" class="login-box visible widget-box no-border">
                            <div class="widget-body">
                                <div class="widget-main">
                                    <h4 class="header blue lighter bigger">
                                        <i class="ace-icon fa fa-coffee green"></i>
                                        请输入用户名密码
                                    </h4>
                                    <div class="space-6"></div>
                                    <form action="<?php echo $this->url->get("/login/login") ?>" id="login">
                                        <fieldset>
                                            <label class="block clearfix form-group">
                                <span class="block input-icon input-icon-right">
                                    <input id="u_name" name="u_name" class="form-control" placeholder="用户名"/>
                                    <i class="ace-icon fa fa-user"></i>
                                </span>
                                            </label>

                                            <label class="block clearfix form-group">
                                <span class="block input-icon input-icon-right">
                                    <input type="password" id="u_pass" name="u_pass" class="form-control"
                                           placeholder="密码"/>
                                    <i class="ace-icon fa fa-lock"></i>
                                </span>
                                            </label>
                                            <div class="space"></div>
                                            <div class="clearfix">
                                                <label class="inline">
                                                </label>
                                                <button type="submit"
                                                        class="width-35 pull-right btn btn-sm btn-primary">
                                                    <i class="ace-icon fa fa-key"></i>
                                                    <span class="bigger-110">登录</span>
                                                </button>
                                            </div>
                                            <div class="space-4"></div>
                                        </fieldset>
                                    </form>
                                </div><!-- /.widget-main -->
                            </div><!-- /.widget-body -->
                        </div><!-- /.login-box -->
                    </div><!-- /.position-relative -->
                </div>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.main-content -->
</div><!-- /.main-container -->

<!-- basic scripts -->

<!--[if !IE]> -->
<script src="<?= $assetUri ?>ace/js/jquery-2.1.4.min.js"></script>

<!-- <![endif]-->

<!--[if IE]>
<script src="<?= $assetUri ?>ace/js/jquery-1.11.3.min.js"></script>
<![endif]-->
<script src="<?php echo $assetUri; ?>ace/js/jquery.validate.min.js"></script>
<script src="<?php echo $assetUri; ?>ace/js/jquery.validate_messages_cn.js"></script>
<link rel="stylesheet" href="<?php echo $assetUri; ?>ace/css/sweetalert.css">
<script src="<?= $assetUri ?>ace/js/sweetalert.min.js"></script>
<script src="<?php echo $assetUri; ?>js/helper.js"></script>
<script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script src='<?= $assetUri ?>ace/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
</script>

<!-- inline scripts related to this page -->
<script type="text/javascript">
    $('#login').validate({
        errorElement: 'div',
        errorClass: 'help-block',
        focusInvalid: true,
        onsubmit: true,
        ignore: "",
        rules: {
            u_name:{
                required:true
            },
            u_pass:{
                required:true
            }
        },
        messages: {
            u_name:{
                required:'必须输入用户名'
            },
            u_pass:{
                required:'必须输入密码'
            }
        },
        highlight: function (e) {
            $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
        },
        success: function (e) {
            $(e).closest('.form-group').removeClass('has-error');//.addClass('has-info');
            $(e).remove();
        },
        errorPlacement: function (error, element) {
            if (element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
                var controls = element.closest('div[class*="col-"]');
                if (controls.find(':checkbox,:radio').length > 1) controls.append(error);
                else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
            }
            else if (element.is('.select2')) {
                error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
            }
            else if (element.is('.chosen-select')) {
                error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
            }
            else error.insertAfter(element.parent());
        },
        submitHandler: function (form) {
            var url = $(form).attr('action');
            var data = $(form).serialize();
            $.ajax({
                url: url,
                data: data,
                dataType: 'json',
                success: function (json) {
                    if(json.status==='success'){
                        helper.alertSuccess(json.message);
                        if(json.goUrl){
                            helper.go(json.goUrl,2);
                        }
                    }else{
                        helper.formShowError(json.errInput,form);
                        helper.alertError(json.message,10);
                    }
                }
            });
            return false;
        },
        invalidHandler: function (form) {
        }
    });
</script>
</body>
</html>
