<?php
if (empty($assetUri)) {
    $assetUri = 'http://static.e.com/';
}

$adminName=isset($adminInfo['u_nick'])?$adminInfo['u_nick']:'未登录';

?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
    <?php echo $this->tag->getTitle() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/font-awesome/4.5.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/jquery-ui.min.css"/>
    <link rel="stylesheet" href="<?php echo $assetUri; ?>ace/css/ui.jqgrid.min.css"/>
    <!-- text fonts -->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/fonts.googleapis.com.css"/>
    <!-- ace styles -->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style"/>
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-part2.min.css" class="ace-main-stylesheet"/>
    <![endif]-->
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-skins.min.css"/>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-rtl.min.css"/>
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="<?= $assetUri ?>ace/css/ace-ie.min.css"/>
    <![endif]-->
    <!-- ace settings handler -->
    <script src="<?= $assetUri ?>ace/js/ace-extra.min.js"></script>
    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->
    <!--[if lte IE 8]>
    <script src="<?= $assetUri ?>ace/js/html5shiv.min.js"></script>
    <script src="<?= $assetUri ?>ace/js/respond.min.js"></script>
    <![endif]-->
    <!--[if !IE]> -->
    <script src="<?= $assetUri ?>ace/js/jquery-2.1.4.min.js"></script>
    <!-- <![endif]-->
    <!--[if IE]>
    <script src="<?= $assetUri ?>ace/js/jquery-1.11.3.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        if ('ontouchstart' in document.documentElement) document.write("<script src='/ace/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>
    <script src="<?php echo $assetUri; ?>ace/js/jquery.jqGrid.min.js"></script>
    <script src="<?php echo $assetUri; ?>ace/js/grid.locale-zh.js"></script>
    <script src="<?= $assetUri ?>js/dataGridHelper.js"></script>
    <script src="<?= $assetUri ?>js/helper.js"></script>
    <!-- basic scripts -->
    <script src="<?= $assetUri ?>ace/js/bootstrap.min.js"></script>
    <!--[if lte IE 8]>
    <script src="<?= $assetUri ?>ace/js/excanvas.min.js"></script>
    <![endif]-->
    <script src="<?= $assetUri ?>ace/js/jquery-ui.min.js"></script>
    <script src="<?php echo $assetUri; ?>ace/js/jquery.ui.datepicker-zh-CN.js"></script>
    <script src="<?= $assetUri ?>ace/js/jquery.ui.touch-punch.min.js"></script>
    <!-- ace scripts -->
    <script src="<?= $assetUri ?>ace/js/ace-elements.min.js"></script>
    <script src="<?= $assetUri ?>ace/js/ace.min.js"></script>
<!--    <script src="--><?//= $assetUri ?><!--ace/js/bootbox.js"></script>-->

    <script src="<?php echo $assetUri; ?>ace/js/jquery.validate.min.js"></script>
    <script src="<?php echo $assetUri; ?>ace/js/jquery.validate_messages_cn.js"></script>
    <link rel="stylesheet" href="<?php echo $assetUri; ?>ace/css/sweetalert.css">
    <script src="<?= $assetUri ?>ace/js/sweetalert.min.js"></script>

</head>
<body class="no-skin">
<div id="navbar" class="navbar navbar-default ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="navbar-header pull-left">
            <a href="/" class="navbar-brand">
                <small>
                    <i class="fa fa-leaf"></i>
                    e家神灯商户管理中心
                </small>
            </a>
        </div>
        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="purple dropdown-modal" style="display: none;">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="ace-icon fa fa-bell icon-animated-bell"></i>
                        <span class="badge badge-important">8</span>
                    </a>
                    <ul class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="ace-icon fa fa-exclamation-triangle"></i>
                            8条通知
                        </li>
                        <li class="dropdown-content">
                            <ul class="dropdown-menu dropdown-navbar navbar-pink">
                                <li>
                                    <a href="#">
                                        <div class="clearfix">
													<span class="pull-left">
														<i class="btn btn-xs no-hover btn-pink fa fa-comment"></i>
														New Comments
													</span>
                                            <span class="pull-right badge badge-info">+12</span>
                                        </div>
                                    </a>
                                </li>

                            </ul>
                        </li>
                        <li class="dropdown-footer">
                            <a href="#">
                                查看更多
                                <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="light-blue dropdown-modal">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="<?= $assetUri ?>ace/images/avatars/user.jpg"
                             alt="Jason's Photo"/>
                        <span class="user-info"><small>欢迎光临,</small><?php echo $adminName ?></span>
                        <i class="ace-icon fa fa-caret-down"></i>
                    </a>
                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="#">
                                <i class="ace-icon fa fa-cog"></i>
                                个人设置
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->url->get('login/outLogin') ?>">
                                <i class="ace-icon fa fa-power-off"></i>
                                退出登录
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.navbar-container -->
</div>
<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
        try {
            ace.settings.loadState('main-container')
        } catch (e) {
        }
    </script>
    <div id="sidebar" class="sidebar responsive ace-save-state">
        <script type="text/javascript">
            try {
                ace.settings.loadState('sidebar')
            } catch (e) {
            }
        </script>
        <?php
        if(file_exists(__DIR__ . '/layouts/menu.phtml')){
            include __DIR__ . '/layouts/menu.phtml';
        }
        ?>
        <!-- /.nav-list -->
        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
            <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state"
               data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>
    </div>
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">首页</a>
                    </li>
                    <?php if (!empty($breadCrumb) && is_array($breadCrumb)): ?>
                        <?php foreach ($breadCrumb as $key => $value): ?>
                            <?php if (empty($value['url'])): ?>
                                <li class="active"><?= $value['text'] ?></li>
                            <?php else: ?>
                                <li class="active"><a href="<?= $value['url'] ?>"><?= $value['text'] ?></a></li>
                            <?php endif ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </ul><!-- /.breadcrumb -->
                <div class="nav-search" id="nav-search">
                    <!--做提示信息用-->
                </div><!-- /.nav-search -->
            </div>
            <?php echo $this->getContent(); ?>
        </div>
    </div><!-- /.main-content -->
    <div class="footer" style="padding-top: 35px">
        <div class="footer-inner">
            <div class="footer-content" style="margin: 0;padding: 0;border-top: solid 1px #E5E5E5;line-height: normal">
                <span class="bigger-100"><span
                            class="blue bolder">汇川集团</span>&copy; 2013-<?php echo date('Y') + 1 ?></span>
            </div>
        </div>
    </div>
    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div><!-- /.main-container -->
</body>
</html>
<?php  \Common\Helpers\TimeHelper::Test() ?>

